(function(){function q(a){var b=new XMLHttpRequest;b.open("GET","https://auth3.acestream.net/c?a="+a,!0);b.timeout=3E4;b.onreadystatechange=function(){if(4==b.readyState&&200==b.status){var a=b.responseText;a&&k({method:"_a",params:{a:n,b:a},onsuccess:function(a){a&&(l=a)},onerror:function(a){}})}};b.send()}function p(a,b,c){try{var d=new XMLHttpRequest,e="http://127.0.0.1:6878/webui/api/service?method=get_version";null===m&&(e+="&params=device-id");d.open("GET",e,!0);d.timeout=1E4;d.onreadystatechange=
function(){if(4==d.readyState){var f="",e=null,g=0;if(200==d.status){var h=JSON.parse(d.responseText);h.error?(g=0,e=null,f=h.error):h.result?(g=parseInt(h.result.code),isNaN(g)&&(g=0),e=h.result.version,h.result.device_id&&m!==h.result.device_id&&(m=h.result.device_id,n&&q(m))):(g=0,e=null,f="malformed response from engine")}else g=0,e=null,f="engine returned error: "+d.status;f&&console.log("checkEngine: error: "+f);"function"===typeof a&&(!g&&void 0!==b&&0<b?(console.log("Ace Script: check engine failed ("+
b+"), next try in "+c),window.setTimeout(function(){p(a,b-1,c)},c)):a.call(null,{running:!!g,versionCode:g,versionString:e}))}};d.send()}catch(f){console.log("checkEngine: error: "+f)}}function r(a){var b,c,d=[];for(b in a)c=a[b],d.push(b+"="+encodeURIComponent(c));return d.join("&")}function k(a){function b(b){console.log("engineapi:request failed: "+b);"function"===typeof a.onerror&&a.onerror.call(null,b)}try{if(!a.method)throw"missing method";a.params||(a.params={});a.api||(a.api="server");a.params.method=
a.method;var c;if("server"==a.api)c="http://127.0.0.1:6878/server/api";else if("service"==a.api)c="http://127.0.0.1:6878/webui/api/service";else throw"unknown api: "+a.api;var d=c+"?"+r(a.params),e=new XMLHttpRequest;e.open("GET",d,!0);e.timeout=1E4;e.onreadystatechange=function(){if(4==e.readyState)if(200==e.status)try{var c=JSON.parse(e.responseText);c.error?b(c.error):c.result?"function"===typeof a.onsuccess&&a.onsuccess.call(null,c.result):b("malformed response from engine")}catch(d){b(d)}else b("engine returned error: "+
e.status)};e.send()}catch(f){AWE_util.logError(f)}}var m=null,l=null,n=null;Registry.register("engineapi","58",{init:function(a){n=a},getEngineStatus:function(a){if("function"!==typeof a)throw"missing callback in getEngineStatus()";p(function(b){function c(b,c){a.call(null,{running:b,version:c})}b.running?c(b.running,b.versionCode):chrome.runtime.sendNativeMessage("org.acestream.engine",{method:"get_version"},function(a){"undefined"===typeof a?(console.log("Ace Script: engine messaging host failed"),
c(!1,0)):(console.log("Ace Script: got response from engine messaging host: "+JSON.stringify(a)),chrome.runtime.sendNativeMessage("org.acestream.engine",{method:"start_engine"},function(a){"undefined"===typeof a?(console.log("Ace Script: failed to start engine"),c(!1,0)):p(function(a){console.log("Ace Script: engine status after starting: "+JSON.stringify(a));c(a.running,a.versionCode)},20,1E3)}))})})},startJsPlayer:function(a){chrome.runtime.sendNativeMessage("org.acestream.engine",{method:"get_version"},
function(b){"undefined"===typeof b?(console.log("Ace Script:startJsPlayer: engine messaging host failed"),a.call(null,!1)):(console.log("Ace Script:startJsPlayer: got response from engine messaging host: "+JSON.stringify(b)),chrome.runtime.sendNativeMessage("org.acestream.engine",{method:"start_js_player"},function(b){"undefined"===typeof b?(console.log("Ace Script:startJsPlayer: failed to start js player"),a.call(null,!1)):a.call(null,b)}))})},getAvailablePlayers:function(a,b){if("function"===typeof b){var c=
{};a.content_id?c.content_id=a.content_id:a.transport_file_url?c.url=a.transport_file_url:a.infohash?c.infohash=a.infohash:b.call(null);k({method:"get_available_players",params:c,onsuccess:function(a){b.call(null,a)},onerror:function(a){b.call(null)}})}},openInPlayer:function(a,b,c){var d={};l&&(d.a=l);a.content_id?d.content_id=a.content_id:a.transport_file_url?d.url=a.transport_file_url:a.infohash?d.infohash=a.infohash:c.call(null);b&&(d.player_id=b);k({method:"open_in_player",params:d,onsuccess:function(a){"function"===
typeof c&&c.call(null,a)},onerror:function(a){"function"===typeof c&&c.call(null)}})},getDeviceId:function(a,b){k({api:"service",method:"get_public_user_key",onsuccess:function(a){"function"===typeof b&&b.call(null,a)},onerror:function(a){"function"===typeof b&&b.call(null)}})},a:function(){return l}})})();
