Registry.require(["promise","helper","convert"],function(){var f=Registry.get("promise"),q=Registry.get("helper"),l=Registry.get("convert"),h=function(){var c=f();Registry.vendor(["vendor/saveas/filesaver"],function(){h=f.Pledge;c.resolve()});return c.promise()},m=function(){var c=f();Registry.vendor(["vendor/zip_js/zip","vendor/zip_js/inflate","vendor/zip_js/deflate"],function(){m=f.Pledge;zip.workerScriptsPath=rea.extension.getURL("/vendor/zip_js/");c.resolve()});return c.promise()},k=function(){var c,
e=!1,d;return{write:function(){var a=f();e=!1;zip.createWriter(new zip.BlobWriter,function(b){c=b;a.resolve(b)},a.reject);return a.promise()},open:function(a){var b=d=f();e=!0;zip.createReader(new zip.BlobReader(a),function(a){c=a;b.resolve(a)},function(a){d&&d.reject(a)});return b.promise()},entries:function(){var a=d=f();c.getEntries(function(b){a.resolve(b)});return a.promise()},get:function(a){var b=d=f(),c=new zip.TextWriter;a.getData(c,b.resolve);return b.promise()},put:function(a,b,e){var g=
d=f();try{c.add(a,new zip.TextReader(b),g.resolve,function(){},{lastModDate:e?new Date(e):void 0})}catch(k){g.reject(k)}return g.promise()},end:function(){var a=d=f();e?(c.close(),a.resolve()):c.close(a.resolve);return a.promise()}}}(),p={zip:{create:function(c,e){var d=f(),a=0;m().then(function(){return k.write()}).then(function(b){var e=f(),g={},n=function(a,b){var d=[a,b].join(".");if(g[d]){var c;do c=a+" ("+g[d]+")",d=[c,b].join("."),g[d]++;while(g[d]);return n(c,b)}g[d]=1;return d},h=c.length,
u=function(){if(!c.length)return e.resolve();var b=c.shift(),g=n(b.meta.name,"acestream.js"),r=n(b.meta.name,"options.json"),t=n(b.meta.name,"storage.json"),l=JSON.stringify({options:b.options,settings:b.settings,meta:b.meta}),m=b.storage?JSON.stringify(b.storage):null;a+=b.source.length;console.log("porter: add to zip",g,a);d.notify({item:h-c.length,of:h});k.put(g,b.source,b.meta.modified).then(function(){a+=l.length;console.log("porter: add to zip",r,a);return k.put(r,l)}).then(function(){if(!m)return f.Pledge();
a+=m.length;console.log("porter: add to zip",t,a);return k.put(t,m)}).fail(function(a){console.log("porter: add to zip failed",a)}).always(function(){console.log("porter: add to zip -> next round");window.setTimeout(u,5)})};u();return e.promise()}).then(function(){console.log("porter: add global props");return e?k.put("AWE.global.json",JSON.stringify(e)):f.Pledge()}).then(function(){return k.end()}).done(function(a){d.resolve(a)}).fail(function(){d.reject()});return d.promise()},read:function(c){var e=
f(),d;m().then(function(){return k.open(c)}).then(function(a){return k.entries()}).then(function(a){var b=f(),c={},g=a.length,h=function(){if(a.length){var f=a.shift();console.log("porter: read from zip",f.filename);k.get(f).done(function(a){var b=f.filename.match(/(.*)\.(storage\.json|options\.json|global\.json|acestream\.js)$/);if(b&&!(3>b.length))try{var e=b[1],g=b[2];c[e]=c[e]||{};"global.json"==g?d=JSON.parse(a):"acestream.js"==g?c[e].source=a:"options.json"==g?c[e].options=JSON.parse(a):"storage.json"==
g&&(c[e].storage=JSON.parse(a))}catch(h){console.warn("porter: read from zip failed",h)}}).always(function(){e.notify({item:g-a.length,of:g});window.setTimeout(h,5)})}else{var l=[];q.each(c,function(a,b){var c=a.options||{};c.source=a.source;c.storage=a.storage;l.push(c)});b.resolve({scripts:l,global_settings:d})}};h();return b.promise()}).done(function(a){e.resolve(a)}).fail(function(){e.reject()});return e.promise()},download:function(c,e){var d=f();h().then(function(){return p.zip.create(c,e).progress(function(a){d.notify(a)})}).done(function(a){saveAs(a,
"tmScripts.zip");d.resolve.apply(this,arguments)}).fail(function(){d.reject.apply(this,arguments)});return d.promise()}},plain:{download:function(c,e){return h().done(function(){var d=new Blob([e],{type:"text/plain"});saveAs(d,c+".acestream.js")})}},json:{create:function(c,e){var d=f();h().done(function(){var a={created_by:"Ace Script",version:"1",scripts:[],settings:e};c.forEach(function(b){b={name:b.meta.name,options:b.options,storage:b.storage,enabled:b.settings.enabled,position:b.settings.position,
file_url:b.meta.file_url,uuid:b.meta.uuid,source:l.Base64.encode(l.UTF8.encode(b.source))};a.scripts.push(b)});d.resolve(JSON.stringify(a))});return d.promise()},read:function(c){var e=f();h().done(function(){var d=function(a){if(a.trim()){var b=null;try{return b=JSON.parse(a),b.scripts=q.map(b.scripts,function(a){a.source=l.UTF8.decode(l.Base64.decode(a.source));return a}),e.resolve({scripts:b.scripts,global_settings:b.settings})}catch(c){if(-1!=a.search("<body>")){var b=a.indexOf("<body>"),f=a.lastIndexOf("</body>");
if(-1!=b&&-1!=f)return a=a.substr(b+6,f-(b+6)),d(a)}}}e.reject()};d(c)});return e.promise()},download:function(c,e){return h().then(function(){return p.json.create(c,e)}).done(function(c){c=new Blob([c],{type:"text/plain"});saveAs(c,"tmScripts.txt")})}}};Registry.register("porter","58",p)});
