Registry.require(["promise","helper","convert","xmlhttprequest"],function(){var F=rea.FEATURES,d=Registry.get("promise"),D=Registry.get("helper"),G=Registry.get("xmlhttprequest").run,H=Registry.get("convert"),p=0,r=0,w={ePASTEBIN:1,eCHROMESYNC:2,eGOOGLEDRIVE:3},A=[],C=!1,x=null,K=[{method:"HEAD",url:"https://www.google.com",extract:function(d,g){try{var k=g?g.split("\n"):null,h;for(h in k){var n=k[h].split(":"),l=n.shift()||"",I=n.join(":")||"";if("date"==l.trim().toLowerCase()&&I){var J=new Date(I);
if(J)return J.getTime()-(new Date).getTime()}}}catch(p){}return null}},{method:"GET",url:"https://json-time.appspot.com/time.json",extract:function(d,g){try{var k=JSON.parse(d);if(!k.error&&k.datetime){var h=new Date(k.datetime);if(h)return h.getTime()-(new Date).getTime()}}catch(n){}return null}}],u=function(){var m=function(){var n,l=!1,h=null,k=function(a){},m=function(a){h=a.state;console.log("si: sync filesystem state changed to : "+h)},g=function(){var a=d(),e=function(b){console.warn("si: listFiles() error:",
b);a.reject()};n.root.getDirectory("/",{create:!0},function(b){var v=b.createReader(),c=[],d=function(){v.readEntries(function(b){b.length?(c=c.concat(b),d()):a.resolve(c)},e)};d()},e);return a.promise()},p=function(a,e){var b=d(),v=function(e){console.warn("si: writeFileData(",a,") error:",e);b.reject()};n.root.getDirectory("/",{create:!0},function(c){c.getFile(a,{create:!0},function(a){a.createWriter(function(a){a.onwriteend=function(c){a.onwriteend=function(a){b.resolve()};a.onerror=v;c=new Blob([e],
{type:"text/plain"});a.write(c)};a.truncate(0)},v)},v)},v);return b.promise()},t=function(a){var e=d(),b=function(b){console.warn("si: getFileData(",a,") error:",b);e.reject()},c=function(a){var c=new FileReader;c.onloadend=function(){e.resolve(this.result)};c.onerror=b;c.onabort=b;c.readAsText(a)};n.root.getDirectory("/",{create:!0},function(e){e.getFile(a,{},function(a){a.file(function(a){c(a)},b)},b)},b);return e.promise()},q=function(a){var e=d(),b=function(b){console.warn("fileStorage: deleteFile(",
a,") error:",b);e.reject()};n.root.getDirectory("/",{create:!0},function(c){c.getFile(a,{create:!1},function(a){a.remove(e.resolve,b)},b)},b);return e.promise()},f=null,z={},c=function(){return B(function(){var a=d(),e=[];D.each(z,function(a,c){e.push(function(){var e=d();p(c,a).always(function(){e.resolve()});return e.promise()}())});z={};d.when(e).done(function(){a.resolve()});return a.promise()})};return{init:function(){if(!l){try{rea.syncFileSystem.onFileStatusChanged.addListener(k)}catch(e){console.log("si: error registering file status callback: "+
e.message)}if(F.SYNC.GOOGLE_DRIVE.HAS_SERVICE_STATUS)try{rea.syncFileSystem.onServiceStatusChanged.addListener(m)}catch(e){console.log("si: error registering service status callback: "+e.message)}l=!0}var a=d();rea.syncFileSystem.supported?rea.syncFileSystem.requestFileSystem(function(e){rea.runtime.lastError?a.resolve(!1):(n=e,a.resolve(!0))}):a.resolve(!1);return a.promise()},list:function(){return g().then(function(a){var e=[],b=[],c=d(),f=/.acestream.js$/;a.forEach(function(a){-1!=a.search(f)&&
b.push(function(){var b=d();t(a).done(function(a){var b;try{b=JSON.parse(a)}catch(c){}b&&e.push({uuid:b.uuid,url:b.url,options:b.options?b.options:{},content:b.content})}).always(function(){b.resolve()});return b.promise()}())});d.when(b).done(function(){c.resolve(e)});return c.promise()})},add:function(a){z[a.uuid+".acestream.js"]=JSON.stringify({uuid:a.uuid,url:a.url,options:a.options,content:a.content});f&&window.clearTimeout(f);f=window.setTimeout(c,3E3);return d.Pledge()},write:c,remove:function(a){var e=
{uuid:a.uuid,url:a.url,options:a.options||{}};e.options.removed=(new Date).getTime()+x;z[a.uuid+".acestream.js"]=JSON.stringify(e);f&&window.clearTimeout(f);f=window.setTimeout(c,3E3);return d.Pledge()},reset:function(){return g().then(function(a){var c=[],b=d();a.forEach(function(a){c.push(function(){var b=d();q(a).always(function(){b.resolve()});return b.promise()}())});d.when(c).done(function(){b.resolve()});return b.promise()})}}}(),g=function(){var h=!1,l,k=function(c,a){if(p==w.eCHROMESYNC&&
"sync"==a)if(null===x)E().done(function(){k(c,a)});else{var e=RegExp(l+"$"),b;for(b in c){var d=c[b];console.log('si: storage key "%s" in namespace "%s" changed. Old value was "%s", new value is "%s".',b,a,d.oldValue,d.newValue);if(-1==b.search(e))console.log("si:   ^^ ignore cause this is not related to us!");else for(var f=0;f<A.length;f++)if(q[b])console.log("si:   ^^ ignore cause object is going to be changed right now or was changed by me!");else{var h=u(d.newValue,b);if(h)A[f](b,h)}}}},g=function(c,
a){var e=d(),b=[];a?m().done(function(d){"url"==c&&(a=a.split("#")[0]);b=D.select(d,function(b){return b.item&&b.item[c]==a});e.resolve(b)}).fail(function(a){e.reject(a)}):e.resolve(b);return e.promise()},m=function(){return B(function(){var c=d(),a=RegExp(l+"$");rea.storage.sync.get(null,function(e){var b=[],d;for(d in e)-1!=d.search(a)&&b.push({key:d,item:u(e[d],d)});c.resolve(b)});return c.promise()})},u=function(c,a){var e=null;try{e=JSON.parse(c)}catch(b){}return e&&e.url?e:(console.warn("si: unable to parse extended info of "+
a),null)},y=function(c){return c.then(function(a){var c={};a=D.select(a,function(a,b){if(!c[a.key])return c[a.key]=!0});if(1<a.length){var b=d(),v=[],h=a.pop();a.forEach(function(a){v.push(f(a.key))});d.when(v).done(function(){b.resolve(h)});return b.promise()}return d.Pledge(a[0])})},t=null,q={},f=function(c,a){return B(function(){var a=d();rea.storage.sync.remove(c,function(b){(b=rea.runtime.lastError)?a.reject(b):a.resolve()});return a.promise()})},z=function(c){return B(function(){var a=d();rea.storage.sync.set(q,
function(c){(c=rea.runtime.lastError)?a.reject(c):(q={},a.resolve())});return a.promise()})};return{init:function(){var c=!0;if(!h)try{rea.storage.onChanged.addListener(k),h=!0}catch(a){console.log("si: error registering sync callback: "+a.message),c=!1}2==r?l="@v2":(r=1,l="@us");return d.Pledge(c)},list:function(){return(null===x?E():d.Pledge()).then(function(){return m()}).then(function(c){var a=RegExp(l+"$"),e=[];c.forEach(function(b){var c=b.key;b=b.item;var d=c.replace(a,""),f=null;(f=q[c]?u(q[c],
c):b)&&(1==r||(!f.vmin||r>=f.vmin)&&(!f.vmax||r<=f.vmax))&&e.push({id:d,uuid:f.uuid,url:f.url,options:f.options||{}})});return d.Pledge(e)})},add:function(c){var a=d(),e=2==r?g("uuid",c.uuid):g("url",c.url);y(e).done(function(b){var e;b?(e=b.key,b=b.item):(e=c.uuid+l,b={});b.url=c.url;b.options=c.options||{};2==r&&(b.uuid=c.uuid);q[e]=JSON.stringify(b);t&&window.clearTimeout(t);t=window.setTimeout(z,3E3);a.resolve()});return a.promise()},remove:function(c){var a=d(),e=2==r?g("uuid",c.uuid):g("url",
c.url);y(e).done(function(b){var e;b?(e=b.key,b=b.item):(e=c.uuid+l,b={});b.options=b.options||{};b.options.removed=(new Date).getTime()+x;q[e]=JSON.stringify(b);t&&window.clearTimeout(t);t=window.setTimeout(z,3E3);a.resolve()});return a.promise()},reset:function(){return B(function(){var c=d();rea.storage.sync.clear(function(){q={};c.resolve()});return c.promise()})}}}(),k=function(){var h,g=null,k=function(){var f=d();h?G({method:"GET",retries:3,url:h},{onload:function(d){4==d.readyState&&(200==
d.status?f.resolve(d.responseText):f.reject())},onerror:f.reject}):f.reject({});return f.promise()},m=function(){var f=d();k().done(function(d){r(d).done(function(c){g=H.MD5(d);f.resolve(c)})}).fail(function(d){f.reject(d)});return f.promise()},r=function(f){var h=d(),c=[];try{f=f.replace(/\t/g,"    ");f=f.replace(/\r/g,"\n");f=f.replace(/\n\n+/g,"\n");for(var a=f.split("\n"),e=0;e<a.length;e++){var b=a[e],g=b.split("|");if(3<g.length)console.log("si: can't handle line: "+b);else{var k=g[g.length-
1],m=null,l=null;if(1<g.length)for(var n=g.length-2;0<=n;n--)try{m=JSON.parse(g[n])}catch(p){l=g[n]}c.push({name:l,url:k,options:m||{}})}}}catch(p){console.warn("si: unable to parse data: "+f)}h.resolve(c);return h.promise()},u=function(){var f=d();k().done(function(d){r(d).done(function(c){if(g!=H.MD5(d))for(c=0;c<A.length;c++)A[c]()})}).fail(function(d){f.reject(d)});return f.promise()},y=null,t=function(d){if(y)if(d)window.clearTimeout(y);else return;console.debug("si: schedule sync for periodical run every 18000000 ms");
y=window.setTimeout(function(){y=null;p==w.ePASTEBIN&&u().always(function(){t()})},18E6)},q={init:function(f){h="https://pastebin.com/raw.php?i=%s".replace("%s",f);t(!0);return d.Pledge(!0)},list:function(){return null===x?E().then(function(){return q.list()}):m()}};return q}(),h={};h[w.ePASTEBIN]=k;h[w.eCHROMESYNC]=g;F.SYNC.GOOGLE_DRIVE.SUPPORTED&&(h[w.eGOOGLEDRIVE]=m);return h}(),E=function(){var m=d(),g=0,k=function(){if(g<K.length){var d=K[g],n={method:d.method,url:d.url};console.log("si: determine time offset with server "+
d.url);G(n,{ondone:function(l){4==l.readyState&&(200==l.status?(l=d.extract(l.responseText,l.responseHeaders),null===l?(g++,window.setTimeout(k,1)):(x=l,console.log("si: detected a time offset of "+l+" ms"),m.resolve(!0))):(g++,window.setTimeout(k,1)))}})}else x=0,console.log("si: time offset detection failed!"),m.resolve(!1)};k();return m.promise()},B=function(m,g){var k=d();void 0===g&&(g=3);var h=function(){if(C)window.setTimeout(h,500);else{C=!0;try{m().always(function(){C=!1}).done(function(){k.resolve.apply(this,
arguments)}).fail(function(){0<--g?(console.log("si: some retries left, wait for",6E4,"ms"),window.setTimeout(h,6E4)):(console.warn("si: no retries left, skipping this sync request!"),k.reject("no retries left"))})}catch(d){console.warn(d),C=!1,k.reject(d)}}};h();return k.promise()},L={init:function(m,g,k){A=[];p=m;r=g;return u[p]?u[p].init(k).done(function(d){}):d.Breach()},debug:function(d){},addChangeListener:function(d){A.push(d)},isWritable:function(){return p==w.eCHROMESYNC||p==w.eGOOGLEDRIVE},
types:w};["list","add","reset","remove"].forEach(function(m){L[m]=function(){return u[p]&&u[p][m]?u[p][m].apply(this,arguments):d.Pledge()}});Registry.register("syncinfo","58",L)});
