/*******************************************************************************
 *  avast! Online Security plugin - Mustache.js HTML Templates - cross browser
 *  (c) 2014 Avast Corp.
 ******************************************************************************/

var AvastWRC = AvastWRC || {};


AvastWRC.Templates = {
  /**
   * Process templates declaration and append templates to container
   */
  add: function (declaration) {
    function addPart(acc, part) {
      if (part instanceof Array) {
        for (var i = 0; i < part.length; i++) {
          addPart(acc, part[i]);
        }
      } else if (part instanceof Object) {
        // reference within declaration
        if (part.temp) {
          var temp = declaration[part.temp] || AvastWRC.Templates[part.temp];
          addPart(acc, (part.sect !== undefined) ? temp[part.sect] : temp);
        }
      } else {
        acc.push(part);
      }
    }

    for (var temp in declaration) {
      var parts = [];
      addPart(parts, declaration[temp]);
      this[temp] = parts.join('\n');
    }
  }
};

/*------------------------ SafeShop bar UI templates -------------------------*/
AvastWRC.Templates.add(
  { // --- Templates Declaration
    safeShopPanel:[
      '<div translate="no" class="notranslate a-sp-panel" id="a-panel">',
        '<div class="a-sp-panel-header" id="a-panel-header">',
          '<img class="a-sp-header-top-left" src="{{images.logo}}"/>',
          '<div class="a-sp-header-top-right">',
          '<div class="sp-header-top-close" id="closePanel" style="background-image: url({{images.close}});">',
          '</div>', 
          '<div class="sp-header-top-min"  id="minPanel" style="background-image: url({{images.min}});">',
          '</div>',
          '<div class="sp-header-top-settings"  id="settingsPanel" style="background-image: url({{images.settings}});">',
          '</div>',
          '</div>',
          '<div class="a-sp-header-bottom-col1" id="offersTab">{{strings.spOffersTab}}<span id="offersTabState" class="{{^offersToBeShown}}a-sp-shown{{/offersToBeShown}}{{#offersToBeShown}}a-sp-to-be-shown{{/offersToBeShown}}"/>',          
          '</div>',
          '<div class="a-sp-header-bottom-separator-1-2">',
          '</div>',
          '<div class="a-sp-header-bottom-col2-selected" id="couponsTab">{{strings.spCouponsTab}}<span id="couponsTabState" class="{{^couponsToBeShown}}a-sp-shown{{/couponsToBeShown}}{{#couponsToBeShown}}a-sp-to-be-shown{{/couponsToBeShown}}"/>',
          '</div>',
          '<div class="a-sp-header-bottom-separator-2-3">',
          '</div>',
          '<div class="a-sp-header-bottom-col3" id="othersTab">{{strings.spOthersTab}}<span id="othersTabState" class="{{^othersToBeShown}}a-sp-shown{{/othersToBeShown}}{{#othersToBeShown}}a-sp-to-be-shown{{/othersToBeShown}}"/>',
          '</div>',
        '</div>',
        '<div class="a-sp-items-wrapper">',
          '<div id="offersWrapper">',
            {temp: 'nothingFoundOffers'},
          '</div>',
          '<div id="couponsWrapper">',
            {temp: 'nothingFoundCoupons'},
          '</div>',
          '<div id="othersWrapper">',
            {temp: 'nothingFoundOthers'},
          '</div>',
        '</div>',
        // '<div class="asp-items-scrollbar-wrapper">',
        //   '<div class="asp-items-scrollbar"></div>',
        // '</div>',    
      '</div>',
    ],

    safeShopMinimizedPanel: [
        '<div id="asp-panel-min" class="asp-panel-minimized a-sp-notifications-hidden">',
        '<img class="asp-panel-minimized-logo" src="{{templateData.images.loadingNotificationLogo}}"/>',
            '<div class="asp-panel-badge">',
              '<div class="asp-panel-badge-text"></div>',
            '</div>',
        '</div>',
    ],

    //
    nothingFoundOffers:[
      '<div class="asp-nothing-found">',
        '<img class="nothing-found-icon" src="{{images.nothingFound}}"></img>',
        '<div class="nothing-found-text">{{{strings.spNothingFoundOffers}}}</div>',
      '</div>',
    ],
    nothingFoundCoupons:[
      '<div class="asp-nothing-found">',
        '<img class="nothing-found-icon" src="{{images.nothingFound}}"></img>',
        '<div class="nothing-found-text">{{{strings.spNothingFoundCoupons}}}</div>',
      '</div>',
    ],
    nothingFoundOthers:[
      '<div class="asp-nothing-found">',
        '<img class="nothing-found-icon" src="{{images.nothingFound}}"></img>',
        '<div class="nothing-found-text">{{{strings.spNothingFoundOthers}}}</div>',
      '</div>',
    ],
    // SafeShop Products dropdown
    offersWrapper:[
        '<div id="offersWrapper">',
        '{{#hotelsPriceComp}}',
          {temp: 'hotelItem'},
        '{{/hotelsPriceComp}}',
        '{{#hotelsCity.length}}',
          '<div class="asp-separator-text-first">{{panelData.strings.spCityHotelNotificationMessage}} <b>{{cityName}}</b></div>',
          '{{#hotelsCity}}',
          {temp: 'hotelItem'},
          '{{/hotelsCity}}',
        '{{/hotelsCity.length}}',
        '{{#hotelsSimilar.length}}',
        '<div class="asp-separator-text-first">{{panelData.strings.spSimilarHotelsMessage}}</div>',
          '{{#hotelsSimilar}}',
          {temp: 'hotelItem'},
          '{{/hotelsSimilar}}',
        '{{/hotelsSimilar.length}}',
        '{{#products}}',
          {temp: 'offerItem'},
        '{{/products}}',
        '</div>',
    ],

    hotelItem:[
      '<div class="asp-offer-item" resurl="{{url}}">',
        '<div class="asp-offer-left">',
          '<img class="asp-offer-item-hotel-image" src="{{affiliate_image}}"/>',
        '</div>',
        '<div class="asp-offer-right">',
          '<div class="asp-offer-first-row">',
            '<div class="asp-offer-item-title">{{label}}</div>',
          '</div>',
          '<div class="asp-offer-second-row">',
            '{{#stars_to_show}}',
              {temp: 'starsRating'},
            '{{/stars_to_show}}',
          '</div>',
          '{{#additional_fees}}',
            '<div class="asp-offer-third-row">',
              '<div class="asp-offer-item-hotel-fee">{{panelData.strings.spAdditionalFees}}</div>',
            '</div>',
          '{{/additional_fees}}',
          '<div class="asp-offer-fourth-row">',
            '{{#is_long_price}}{{#fsaving}}{{#offerQuery.formatted_price}}',
            '<div class="asp-offer-item-price-stroke above">{{offerQuery.formatted_price}}</div>',
            '{{/offerQuery.formatted_price}}{{/fsaving}}{{/is_long_price}}',
          '</div>',
          {temp: 'offerBottomRow'},
        '</div>',
      '</div>'
    ],

    // SafeShop Products list item
    offerItem:[
      '<div class="asp-offer-item" resurl="{{url}}">',
        '<div class="asp-offer-left">',
            '<img class="asp-offer-item-image" src="{{affiliate_image}}"/>',
        '</div>',
        '<div class="asp-offer-right">',
          '<div class="asp-offer-first-row">',
            '<div class="asp-offer-item-title">{{label}}</div>',
          '</div>',
          '<div class="asp-offer-second-row">',
            '{{#shipping}}',
              '<div class="asp-offer-item-shipping">{{panelData.strings.spShippingLabel}} {{shipping}}</div>',
            '{{/shipping}}',
          '</div>',
          '<div class="asp-offer-third-row">',
            '{{#additional_fees}}',
            '<div class="asp-offer-item-hotel-fee">{{panelData.strings.spAdditionalFees}}</div>',
            '{{/additional_fees}}',
          '</div>',
          '<div class="asp-offer-fourth-row">',
            '{{#is_long_price}}{{#fsaving}}{{#offerQuery.formatted_price}}',
              '<div class="asp-offer-item-price-stroke above">{{offerQuery.formatted_price}}</div>',
            '{{/offerQuery.formatted_price}}{{/fsaving}}{{/is_long_price}}',
          '</div>',
          '<div class="asp-offer-fifth-row">',
            {temp: 'offerBottomRow'},
          '</div>',
        '</div>',
      '</div>'
    ],

    offerBottomRow: [
        '{{#is_long_price}}',
            '<div class="asp-offer-fifth-row">',
        '{{/is_long_price}}',
        '{{^is_long_price}}',
          '{{#fsaving}}',
            '<div class="asp-offer-fifth-row top-space">',
          '{{/fsaving}}',
          '{{^fsaving}}',
            '<div class="asp-offer-fifth-row">',
          '{{/fsaving}}',
        '{{/is_long_price}}',
          '{{#fsaving}}',
            '<div class="asp-offer-item-discount-banner"><span class="asp-offer-item-discount-text">{{fsaving}}</span></div>',
          '{{/fsaving}}',
          '{{^fsaving}}',
            '<div class="asp-blank-div"></div>',
          '{{/fsaving}}',
          '{{#is_long_price}}',
            '<div class="asp-blank-div"></div>',
          '{{/is_long_price}}',
          '{{^is_long_price}}',
            '{{#offerQuery.formatted_price}}{{#fsaving}}',
              '<div class="asp-offer-item-price-stroke">{{offerQuery.formatted_price}}</div>',
            '{{/fsaving}}{{/offerQuery.formatted_price}}',
            '{{^offerQuery.formatted_price}}',
              '<div class="asp-blank-div"></div>',
            '{{/offerQuery.formatted_price}}',
          '{{/is_long_price}}',
          '{{#show_price}}',
            '<div class="asp-offer-item-price">{{fprice}}</div>',
          '{{/show_price}}',
          '{{^show_price}}',
            '<div class="asp-blank-div"></div>',
          '{{/show_price}}',
        '</div>'
    ],

    couponsWrapper:[
      '<div id="couponsWrapper">',
        '{{#vouchersSelected}}',
          '<div class="asp-separator-text-first">{{panelData.strings.spCouponsSelectedText}}</div>',
          {temp: 'selectedCoupons'},
          '{{#vouchersAvailable}}<div class="asp-separator-text">{{panelData.strings.spCouponsAvailableText}}</div>{{/vouchersAvailable}}',
          {temp: 'notSelectedCoupons'},
        '{{/vouchersSelected}}',
        '{{^vouchersSelected}}',          
          {temp: 'notSelectedCoupons'},
        '{{/vouchersSelected}}',
      '</div>',
    ],

    notSelectedCoupons:[
      '{{#coupons}}{{^selected}}',
        '<div class="asp-coupon-item" id="coupon" resurl="{{url}}">',
          '<div class="asp-coupon-top">',
            '{{#value}}',
              '<div class="asp-coupon-item-value">{{value}}</div>',
              '<div class="asp-coupon-item-label">{{label}}</div>',
              '{{#coupon_text}}',
                '<div class="asp-coupon-description">',
                  '<div class="asp-coupon-description-text">{{coupon_text}}</div>',
                '</div>',
                '<div class="asp-coupon-description-more-info" id="more-info">{{panelData.strings.spNotificationRedirectShowMoreMessage}}</div>',
              '{{/coupon_text}}',    
              //'{{#expire_date_to_show}}<div class="asp-coupon-expiration">{{panelData.strings.spCouponsExpiration}} {{expire_date_to_show}}</div>{{/expire_date_to_show}}',
            '{{/value}}',
            '{{^value}}',
              '<div class="asp-coupon-item-label-full-size">{{label}}</div>',
              '{{#coupon_text}}', 
                '<div class="asp-coupon-description-full-size">',
                  '<div class="asp-coupon-description-full-size-text">{{coupon_text}}</div>',
                '</div>',
                '<div class="asp-coupon-description-more-info" id="more-info">{{panelData.strings.spNotificationRedirectShowMoreMessage}}</div>',
              '{{/coupon_text}}',        
              //'{{#expire_date_to_show}}<div class="asp-coupon-expiration-full-size">{{panelData.strings.spCouponsExpiration}} {{expire_date_to_show}}</div>{{/expire_date_to_show}}',
            '{{/value}}',
          '</div>',
          '<div class="asp-coupon-separator">',
            '<div class="asp-coupon-separator-left"></div>',
            '<img class="asp-coupon-separator-middle" src="{{panelData.images.dashedLine}}"/>',
            '<div class="asp-coupon-separator-right"></div>',
          '</div>',
          '<div class="asp-coupon-bottom"  id="coupon" resurl="{{url}}">',
          '<div class="asp-coupon-item-get-coupon">',
            '{{#coupon_code}}{{panelData.strings.spGetCouponCode}}{{/coupon_code}}',
            '{{^coupon_code}}{{panelData.strings.spApply}}{{/coupon_code}}',
          '</div>',
          '</div>',
        '</div>',
      '{{/selected}}{{/coupons}}',
    ],

    selectedCoupons:[
      '{{#coupons}}{{#selected}}',        
        '<div class="asp-coupon-item-active{{#coupon_code}}-with-code{{/coupon_code}}" id="coupon" resurl="{{url}}">',
          '<div class="asp-coupon-top">',
            '{{#value}}',
              '<div class="asp-coupon-item-value">{{value}}</div>',
              '<div class="asp-coupon-item-label">{{label}}</div>',
              '{{#coupon_text}}',
                '<div class="asp-coupon-description">',
                  '<div class="asp-coupon-description-text">{{coupon_text}}</div>',
                '</div>',
                '<div class="asp-coupon-description-more-info" id="more-info">{{panelData.strings.spNotificationRedirectShowMoreMessage}}</div>',
              '{{/coupon_text}}',              
              //'{{#expire_date_to_show}}<div class="asp-coupon-expiration">{{panelData.strings.spCouponsExpiration}} {{expire_date_to_show}}</div>{{/expire_date_to_show}}',
            '{{/value}}',
            '{{^value}}',
              '<div class="asp-coupon-item-label-full-size">{{label}}</div>',
              '{{#coupon_text}}', 
                '<div class="asp-coupon-description-full-size">',
                  '<div class="asp-coupon-description-full-size-text">{{coupon_text}}</div>',
                '</div>',
                '<div class="asp-coupon-description-more-info" id="more-info">{{panelData.strings.spNotificationRedirectShowMoreMessage}}</div>',
              '{{/coupon_text}}',
              //'{{#expire_date_to_show}}<div class="asp-coupon-expiration-full-size">{{panelData.strings.spCouponsExpiration}} {{expire_date_to_show}}</div>{{/expire_date_to_show}}',
            '{{/value}}',
          '</div>',
          '<div class="asp-coupon-separator">',
            '<div class="asp-coupon-separator-left"></div>',
            '<img class="asp-coupon-separator-middle" src="{{panelData.images.dashedLine}}"/>',
            '<div class="asp-coupon-separator-right"></div>',
          '</div>',          
          '{{#coupon_code}}',
            '<div class="asp-coupon-bottom-with-code" cupcod="{{coupon_code}}">', 
              '<div class="asp-coupon-item-copy-code">{{panelData.strings.spCopyAtCheckOut}}</div>',
              '<div class="asp-coupon-item-coupon-code">{{coupon_code}}</div>',
            '</div>',
          '{{/coupon_code}}',
          '{{^coupon_code}}',
            '<div class="asp-coupon-bottom-without-code">',
              '<div class="asp-coupon-item-coupon-applied">{{panelData.strings.spCouponApplied}}</div>',
            '</div>',
          '{{/coupon_code}}',          
        '</div>',
      '{{/selected}}{{/coupons}}',
    ],

    activeCoupons:[
      '{{#vouchersSelected}}{{#vouchersSelectedCounter}}',
        '<div class="a-sp-active-coupons-message" id="activeCoupons">',
          '<div class="a-sp-active-coupons-info">{{panelData.strings.spCouponsSelected}}',
              '<span class="asp-active-coupons-badge{{#vouchersCounterBig}}-big{{/vouchersCounterBig}}">{{vouchersSelectedCounter}}</span>',            
          '</div>',         
        '</div>',
        '{{/vouchersSelectedCounter}}{{/vouchersSelected}}',
    ],

    othersWrapper:[
      '<div id="othersWrapper">',
        '{{#isRedirect}}',
          '<div class="asp-redirect-item" id="redirect" resurl="{{url}}">',
            {temp: "notificationRedirectContent"},  
          '</div>',
        '{{/isRedirect}}',
        '{{#isSimilarCoupons}}',
          '<div class="asp-similar-coupon-item" id="similarCoupon" resurl="{{similarCoupon.url}}">',
            {temp: "similarCouponsNotification"},  
            {temp: "notificationsButton"},  
          '</div>',
        '{{/isSimilarCoupons}}',
      '</div>',
    ],

    starsRating: [
        '<div class="asp-rating-stars-wrapper">',
        '{{#stars}}',
        '<i class="asp-rating-star" style="background-image: url({{.}});"></i>',
        '{{/stars}}',
        '</div>'
    ],

    copiedToClipboard: [
      '<div class="asp-copied-to-clipboard">{{panelData.strings.sasCouponCodeCopied}}</div>'
    ],

    safeShopSettingsPopup : [
      '<div class="avast-sas-settings-page">',
        '<div class="avast-sas-settings-poppup">',
          '{{^isChrome}}{{^isAvast}}',
            '<div class="avast-sas-settings-title-box">',
              '{{#isFirefox}}',
                '<div class="avast-sas-settings-title-text">{{poppupSettings.strings.sasHintSettings}}</div>',
              '{{/isFirefox}}',
              '{{^isFirefox}}',
                '<img class="avast-sas-settings-title-icon" src={{poppupSettings.images.logo}}></img>',
                '<div class="avast-sas-settings-title-text">',
                  '{{#avastBranding}}',
                    '{{poppupSettings.strings.spSettingsPageTitleAvast}}',
                  '{{/avastBranding}}',
                  '{{^avastBranding}}',
                    '{{poppupSettings.strings.spSettingsPageTitleAvg}}',
                  '{{/avastBranding}}',
                '</div>',
                '<div class="avast-sas-settings-title-close" id="avast-sas-popup-settings-close" style="background-image: url({{poppupSettings.images.close}});"></div>',
              '{{/isFirefox}}',
            '</div>',
          '{{/isAvast}}{{/isChrome}}',
          '<div class="avast-sas-middle-box">',
            '<div class="avast-sas-middle-menu">',
              '<div class="avast-sas-middle-item-notifications{{#poppupSettings.menuOpt.notifications.selected}}-selected{{/poppupSettings.menuOpt.notifications.selected}}" id="sp-menu-notifications">',
                '{{poppupSettings.strings.spSettingsTabNotifications}}',
              '</div>', 
              '<div class="avast-sas-middle-item-custom-list{{#poppupSettings.menuOpt.customList.selected}}-selected{{/poppupSettings.menuOpt.customList.selected}}" id="sp-menu-customList">',
                '{{poppupSettings.strings.spSettingsPageCustomList}}',
              '</div>', 
              '<div class="avast-sas-middle-item-help{{#poppupSettings.menuOpt.help.selected}}-selected{{/poppupSettings.menuOpt.help.selected}}" id="sp-menu-help">',
                '{{poppupSettings.strings.spSettingsPageHelp}}',
              '</div>', 
            '</div>',
            '<div class="avast-sas-middle-options">',
              '<div class="avast-sas-middle-panel-notifications {{#poppupSettings.menuOpt.notifications.selected}}avast-sas-display-grid{{/poppupSettings.menuOpt.notifications.selected}}" id="sp-panel-notifications-options">',
                '<div class="avast-sas-p-a-title-offers">',
                  '{{poppupSettings.strings.spSettingsTabNotificationsOffers}}',
                '</div>',
                '<div class="avast-sas-p-a-box-1{{#poppupSettings.menuOpt.notifications.offers.item1Selected}}-selected{{/poppupSettings.menuOpt.notifications.offers.item1Selected}}" id="avast-sas-p-a-box-1">',
                  '<div class="avast-sas-radio-button">',
                  '</div>',
                  '<div class="avast-sas-radio-button-desc">',
                    '{{poppupSettings.strings.spSettingsTabNotificationsOffersShowAll}}',
                  '</div>',
                '</div>',
                '<div class="avast-sas-p-a-box-2{{#poppupSettings.menuOpt.notifications.offers.item2Selected}}-selected{{/poppupSettings.menuOpt.notifications.offers.item2Selected}}" id="avast-sas-p-a-box-2">',
                  '<div class="avast-sas-radio-button">',
                  '</div>',
                  '<div class="avast-sas-radio-button-desc">',
                    '{{poppupSettings.strings.spSettingsTabNotificationsOffersBetter}}',
                  '</div>',
                '</div>',
                '<div class="avast-sas-p-a-box-3{{#poppupSettings.menuOpt.notifications.offers.item3Selected}}-selected{{/poppupSettings.menuOpt.notifications.offers.item3Selected}}" id="avast-sas-p-a-box-3">',
                  '<div class="avast-sas-radio-button">',
                  '</div>',
                  '<div class="avast-sas-radio-button-desc">',
                    '{{poppupSettings.strings.spSettingsTabNotificationsOffersBetterThanLimit}}',
                  '</div>',
                '</div>',
                '<div class="avast-sas-p-g-box-1{{#poppupSettings.menuOpt.notifications.offers.item4Selected}}-selected{{/poppupSettings.menuOpt.notifications.offers.item4Selected}}" id="avast-sas-p-g-box-1">',
                    '<div class="avast-sas-radio-button">',
                    '</div>',
                    '<div class="avast-sas-radio-button-desc">',
                      '{{poppupSettings.strings.spSettingsTabNotificationsOffersHideAll}}',
                    '</div>',
                    '<div class="avast-sas-radio-button-option-desc">',
                      '{{poppupSettings.strings.spSettingsTabNotificationsOffersHideAllDesc}}',
                    '</div>',
                '</div>',
                '<div class="avast-sas-p-a-include-offers">',
                  '<div class="avast-sas-text-include-offers">',
                    '{{poppupSettings.strings.spSettingsPageAdvancedItemInclude}}',
                  '</div>',
                  '<div class="avast-sas-text-include-button-1-1" id="include-eShop-offers">',
                    '{{#poppupSettings.menuOpt.notifications.offers.include.eShop}}<img class="asp-check-box"src="{{poppupSettings.images.checkboxChecked}}" id="include-eShop-offers-checkbox">{{/poppupSettings.menuOpt.notifications.offers.include.eShop}}',
                    '{{^poppupSettings.menuOpt.notifications.offers.include.eShop}}<img class="asp-check-box"src="{{poppupSettings.images.checkbox}}" id="include-eShop-offers-checkbox">{{/poppupSettings.menuOpt.notifications.offers.include.eShop}}',
                    '<div class="avast-sas-check-box-desc">{{poppupSettings.strings.spSettingsPageAdvancedItemIncludeEShop}}</div>',
                  '</div>',
                  '<div class="avast-sas-text-include-button-1-2" id="include-accommodations-offers">',
                    '{{#poppupSettings.menuOpt.notifications.offers.include.accommodations}}<img class="asp-check-box" src="{{poppupSettings.images.checkboxChecked}}" id="include-accommodations-offers-checkbox">{{/poppupSettings.menuOpt.notifications.offers.include.accommodations}}',
                    '{{^poppupSettings.menuOpt.notifications.offers.include.accommodations}}<img class="asp-check-box"src="{{poppupSettings.images.checkbox}}" id="include-accommodations-offers-checkbox">{{/poppupSettings.menuOpt.notifications.offers.include.accommodations}}',
                    '<div class="avast-sas-check-box-desc">{{poppupSettings.strings.spSettingsPageAdvancedItemIncludeAccomm}}</div>',
                  '</div>',
                '</div>',
                '<div class="avast-sas-p-a-title-coupons">',
                  '{{poppupSettings.strings.spSettingsTabNotificationsCoupons}}',
                '</div>',
                '<div class="avast-sas-p-a-box-4{{#poppupSettings.menuOpt.notifications.coupons.item1Selected}}-selected{{/poppupSettings.menuOpt.notifications.coupons.item1Selected}}" id="avast-sas-p-a-box-4">',
                  '<div class="avast-sas-radio-button">',
                  '</div>',
                  '<div class="avast-sas-radio-button-desc">',
                    '{{poppupSettings.strings.spSettingsTabNotificationsCouponsShowAll}}',
                  '</div>',
                '</div>',
                '<div class="avast-sas-p-a-box-5{{#poppupSettings.menuOpt.notifications.coupons.item2Selected}}-selected{{/poppupSettings.menuOpt.notifications.coupons.item2Selected}}" id="avast-sas-p-a-box-5">',
                  '<div class="avast-sas-radio-button">',
                  '</div>',
                  '<div class="avast-sas-radio-button-desc">',
                    '{{poppupSettings.strings.spSettingsTabNotificationsCouponsShowOnce}}',
                  '</div>',
                '</div>',
                '<div class="avast-sas-p-g-box-2{{#poppupSettings.menuOpt.notifications.coupons.item3Selected}}-selected{{/poppupSettings.menuOpt.notifications.coupons.item3Selected}}" id="avast-sas-p-g-box-2">',
                  '<div class="avast-sas-radio-button">',
                  '</div>',
                  '<div class="avast-sas-radio-button-desc">',
                    '{{poppupSettings.strings.spSettingsTabNotificationsCouponsHide}}',
                  '</div>',
                  '<div class="avast-sas-radio-button-option-desc">',
                    '{{poppupSettings.strings.spSettingsTabNotificationsCouponsHideDesc}}',
                  '</div>',
                '</div>',
                '<div class="avast-sas-p-a-title-others">',
                  '{{poppupSettings.strings.spSettingsTabNotificationsOthers}}',
                '</div>',
                '<div class="avast-sas-p-a-box-6" id="avast-sas-p-a-box-6">',
                '{{#poppupSettings.menuOpt.notifications.others.item1Selected}}<img class="asp-check-box"src="{{poppupSettings.images.checkboxChecked}}" id="include-others-checkbox">{{/poppupSettings.menuOpt.notifications.others.item1Selected}}',
                '{{^poppupSettings.menuOpt.notifications.others.item1Selected}}<img class="asp-check-box"src="{{poppupSettings.images.checkbox}}" id="include-others-checkbox">{{/poppupSettings.menuOpt.notifications.others.item1Selected}}',
                  '<div class="avast-sas-radio-button-desc">',
                    '{{poppupSettings.strings.spSettingsTabNotificationsOthersDesc}}',
                  '</div>',
                '</div>',
              '</div>',                
              '<div class="avast-sas-middle-panel-custom-list {{#poppupSettings.menuOpt.customList.selected}}avast-sas-display-grid{{/poppupSettings.menuOpt.customList.selected}}"  id="sp-panel-customList-options">',
                '<div class="avast-sas-p-cl-title">',
                  '{{poppupSettings.strings.spSettingsPageCustomListTitle}}',
                '</div>',
                '<div class="avast-sas-p-cl-add-site-button {{#poppupSettings.menuOpt.customList.showAddButton}}avast-sas-display-block{{/poppupSettings.menuOpt.customList.showAddButton}}" id="add-site-button-to-box">',
                  '<div class="avast-sas-p-cl-add-site-button-icon" style="background-image: url({{poppupSettings.images.add}});"></div>', 
                  '<div class="avast-sas-p-cl-add-site-button-text">',
                    '{{poppupSettings.strings.spSettingsPageCustomListItemAddSite}}',
                  '</div>', 
                '</div>',
                '<div class="avast-sas-p-cl-add-site-box {{^poppupSettings.menuOpt.customList.showAddButton}}avast-sas-display-block{{/poppupSettings.menuOpt.customList.showAddButton}}" id="add-site-box">',
                  '<input type="text" class="avast-sas-p-cl-add-site-text" id="new-site-name" autofocus>',
                  '<div class="avast-sas-p-cl-add-site-add" id="add-site-add">',
                    '{{poppupSettings.strings.spSettingsPageCustomListItemAdd}}',
                  '</div>', 
                  '<div class="avast-sas-p-cl-add-site-cancel" id="add-site-cancel">',
                    '{{poppupSettings.strings.spSettingsPageCancel}}',
                  '</div>', 
                '</div>', 
                '<div class="avast-sas-p-cl-sites-box">',
                  '{{#poppupSettings.menuOpt.customList.whiteList.length}}',
                    '{{#poppupSettings.menuOpt.customList.whiteList}}',
                      '<div class="avast-sas-p-cl-box-element">',
                        '<div class="avast-sas-p-cl-box-element-text">',
                          '{{.}}',
                        '</div>',
                        '<div class="avast-sas-p-cl-box-element-close" style="background-image: url({{poppupSettings.images.erase}});">',
                        '</div>',
                      '</div>',
                    '{{/poppupSettings.menuOpt.customList.whiteList}}',
                  '{{/poppupSettings.menuOpt.customList.whiteList.length}}',
                '</div>',
              '</div>',
              '<div class="avast-sas-middle-panel-help {{#poppupSettings.menuOpt.help.selected}}avast-sas-display-grid{{/poppupSettings.menuOpt.help.selected}}"  id="sp-panel-help-options">', 
                '<div class= "avast-sas-help-group-1">',
                  '<div class= "avast-sas-help-title">{{poppupSettings.strings.spSettingsPageHelpNotificationsTitle}}</div>',
                  '<div class= "avast-sas-help-title-desc">{{poppupSettings.strings.spSettingsPageHelpNotificationsTitleDesc}}</div>',
                '</div>',
                '<div class= "avast-sas-help-group-2">',
                  '<div class= "avast-sas-help-title">{{poppupSettings.strings.spSettingsPageHelpOffersTitle}}</div>',
                  '<div class= "avast-sas-help-title-desc">{{poppupSettings.strings.spSettingsPageHelpOffersTitleDesc}}</div>',
                '</div>',
                '<div class= "avast-sas-help-group-3">',
                  '<div class= "avast-sas-help-title">{{poppupSettings.strings.spSettingsPageHelpCouponsTitle}}</div>',
                  '<div class= "avast-sas-help-title-desc">{{poppupSettings.strings.spSettingsPageHelpCouponsTitleDesc}}</div>',
                '</div>',
                '<div class= "avast-sas-help-group-4">',
                  '<div class= "avast-sas-help-title">{{poppupSettings.strings.spSettingsPageHelpOthersTitle}}</div>',
                  '<div class= "avast-sas-help-title-desc">{{poppupSettings.strings.spSettingsPageHelpOthersTitleDesc}}</div>',
                '</div>',
                '<div class= "avast-sas-help-faqs">{{{poppupSettings.strings.spSettingsPageHelpFAQsTitle}}}</div>',
              '</div>',
            '</div>',
          '</div>',
          '<div class="avast-sas-settings-footer-box">',
            '{{^isFirefox}}',
              '<div class="avast-sas-settings-footer-cancel" id="avast-sas-popup-settings-cancel">',
                '{{poppupSettings.strings.spSettingsPageCancel}}',
              '</div>',
            '{{/isFirefox}}',
            '<div class="avast-sas-settings-footer-save" id="avast-sas-poppup-settings-save">',
              '{{poppupSettings.strings.spSettingsPageSave}}',
            '</div>',
          '</div>',
        '</div>',
      '</div>',
    ],

    whiteListElement : [
      '<div class="avast-sas-p-cl-box-element">',
        '<div class="avast-sas-p-cl-box-element-text">',
          '{{site}}',
        '</div>',
        '<div class="avast-sas-p-cl-box-element-close" style="background-image: url({{icon}});">',
        '</div>',
      '</div>',
    ],

    notification: [
        '<div class="a-sp-notifications a-sp-notifications-hidden notranslate" id="a-sp-notifications-standard">',
          '<div class="a-sp-notifications-header" id="a-sp-notifications-header-drag">',
            '<img class="a-sp-notifications-header-logo-icon" src="{{templateData.images.loadingNotificationLogo}}"/>',
            '<img class="a-sp-notifications-header-gear-icon" src="{{templateData.images.loadingNotificationGear}}"/>',
            '<img class="a-sp-notifications-header-close-icon" src="{{templateData.images.loadingNotificationClose}}"/>',
          '</div>',
          '<div class="a-sp-loading-notification a-sp-notifications-hidden">',
            '<img class="a-sp-loading-notification-img" src="{{templateData.images.loadingGIF}}"/>',
            '<p class="a-sp-loading-notification-text">{{{templateData.strings.spLoadingNotificationMessage}}}</p>',
            '<p class="a-sp-loading-notification-description">{{templateData.strings.spLoadingNotificationDescriptionMessage}}</p>',
          '</div>',
          '<div class="a-sp-coupons-notification a-sp-notifications-hidden">',
            '<img class="a-sp-coupons-notification-img" src="{{templateData.images.couponsPanel}}"/>',
            '<img class="a-sp-coupons-notification-img-animated a-sp-notification-img-hidden" src="{{templateData.animations.couponsPanel}}"/>',
            '<p class="a-sp-coupons-notification-text">{{templateData.strings.spCouponsNotificationMessage}}</p>',
          '</div>',
          '<div class="a-sp-offers-notification a-sp-notifications-hidden">',
            '<img class="a-sp-offers-notification-img" src="{{templateData.images.moreOffersPanel}}"/>',
            '<img class="a-sp-offers-notification-img-animated a-sp-notification-img-hidden" src="{{templateData.animations.betterOffersPanel}}"/>',
            '<p class="a-sp-offers-notification-text">{{{templateData.strings.spBetterOffersNotificationMessage}}}</p>',
          '</div>',
          '<div class="a-sp-offers-coupons-notification a-sp-notifications-hidden">',
            '<img class="a-sp-offers-coupons-notification-img" src="{{templateData.images.offersAndCouponsPanel}}"/>',
            '<img class="a-sp-offers-coupons-notification-img-animated a-sp-notification-img-hidden" src="{{templateData.animations.offersAndCouponsPanel}}"/>',
            '<p class="a-sp-offers-coupons-notification-text">{{{templateData.strings.spOffersAndCouponsNotificationMessage}}}</p>',
          '</div>',
          {temp:"similarCouponsNotification"},
          '<div class="a-sp-city-hotels-notification a-sp-notifications-hidden">',
            '<img class="a-sp-city-hotels-notification-img" src="{{templateData.images.hotelsPanel}}">',
            '<img class="a-sp-city-hotels-notification-img-animated a-sp-notification-img-hidden" src="{{templateData.animations.hotelsPanel}}">',
            '<p class="a-sp-city-hotels-notification-text">{{templateData.strings.spCityHotelNotificationMessage}}<br><span class="a-sp-city-hotels-notification-text-city"></span></p>',
          '</div>',
          '<div class="a-sp-similar-hotels-notification a-sp-notifications-hidden">',
            '<img class="a-sp-similar-hotels-notification-img" src="{{templateData.images.hotelsPanel}}"/>',
            '<img class="a-sp-similar-hotels-notification-img-animated a-sp-notification-img-hidden" src="{{templateData.animations.hotelsPanel}}"/>',
            '<p class="a-sp-similar-hotels-notification-text">{{{templateData.strings.spSimilarHotelsNotificationMessage}}}</p>',
          '</div>',
          {temp: "notificationsButton"},
        '</div>',
    ],

    similarCouponsNotification: [
      '<div class="a-sp-deals-notification {{^isPanelTemplate}}a-sp-notifications-hidden{{/isPanelTemplate}}">',
          '<img class="a-sp-deals-notification-img {{#isPanelTemplate}}a-sp-notification-img-hidden{{/isPanelTemplate}}" src="{{templateData.images.specialDealsPanel}}"/>',
          '<img class="a-sp-deals-notification-img-animated {{^isPanelTemplate}}a-sp-notification-img-hidden{{/isPanelTemplate}}" src="{{templateData.animations.specialDealsPanel}}"/>',
          '<p class="a-sp-deals-notification-text">{{{templateData.strings.spBetterSpecialDealsNotificationMessage}}}</p>',
      '</div>',
    ],

    notificationsButton: [
      '<div class="a-sp-notifications-button {{#redirect.infoText}}space-down{{/redirect.infoText}}">',
          '<span class="a-sp-notifications-button-show" {{#isPanelTemplate}}id="similarCouponsButton"{{/isPanelTemplate}} resurl="{{similarCoupon.url}}">',
              '{{templateData.strings.spShowNotificationMessage}}',
          '</span>',
          '<span class="a-sp-notifications-button-show-amount">{{#isPanelTemplate}}{{similarCoupon.value}}{{/isPanelTemplate}}</span>',
      '</div>',
    ],

    notificationRedirect: [
      '<div class="a-sp-notifications-redirect notranslate" id="a-sp-notifications-redirect">',
        '<div class="a-sp-notifications-redirect-header" id="a-sp-notifications-redirect-header-drag">',
            '<img class="a-sp-notifications-redirect-header-logo-icon" src="{{templateData.images.loadingNotificationLogo}}">',
            '<img class="a-sp-notifications-redirect-header-gear-icon" src="{{templateData.images.loadingNotificationGear}}">',
            '<img class="a-sp-notifications-redirect-header-close-icon" src="{{templateData.images.loadingNotificationClose}}">',
        '</div>',        
        {temp: "notificationRedirectContent"},       
      '</div>',
    ],
    notificationRedirectContent: [
      '{{#redirect.image}}',
          {temp: "notificationRedirectImageContainer"},
      '{{/redirect.image}}',
      '{{^redirect.image}}',
          {temp: "notificationRedirectDefaultImageContainer"},
      '{{/redirect.image}}',
      '<div class="a-sp-notifications-redirect-title">{{redirect.label}}</div>',
      '<div class="a-sp-notifications-redirect-price">{{redirect.availability}}</div>',
      '<div class="a-sp-notifications-redirect-button-show" {{#isPanelTemplate}}id="redirectButton"{{/isPanelTemplate}} resurl="{{redirect.url}}">{{templateData.strings.spNotificationRedirectShowRedirectMessage}}</div>',
      '{{#redirect.infoText}}',
          '<div class="a-sp-notifications-redirect-info" {{#isPanelTemplate}}id="redirectMoreInfo"{{/isPanelTemplate}}>',
              '<span class="a-sp-notifications-redirect-info-more a-sp-notifications-redirect-info-toggle-text">{{templateData.strings.spNotificationRedirectShowMoreMessage}}</span>',
              '<span class="a-sp-notifications-redirect-info-less a-sp-notifications-redirect-info-toggle-text a-sp-notifications-hidden">{{templateData.strings.spNotificationRedirectShowLessMessage}}</span>',
              '<img src="{{templateData.images.shape}}" class="a-sp-notifications-redirect-info-icon">',
              '<div class="a-sp-notifications-redirect-info-toggle-text-padding a-sp-notifications-redirect-info-toggle-text"> </div>',
              '<div class="a-sp-notifications-redirect-info-text a-sp-notifications-hidden">{{redirect.infoText}}</div>',
          '</div>',
      '{{/redirect.infoText}}',
    ],
    notificationRedirectImageContainer: [
      '<div class="a-sp-notifications-redirect-image-container">',
        '<div class="a-sp-notifications-redirect-image-title">{{templateData.strings.spShowNotificationRedirectMessage}}</div>',
        '<div class="a-sp-notifications-redirect-image-frame">',
          '<img class="a-sp-notifications-redirect-img" src="{{redirect.image}}" {{#isPanelTemplate}}id="redirectImage"{{/isPanelTemplate}}>',
        '</div>',
      '</div>',
    ],
    notificationRedirectDefaultImageContainer: [
      '<div class="a-sp-notifications-redirect-default-image-container">',
        '<img class="a-sp-notifications-redirect-default-img" src="{{templateData.images.specialDealsGIF}}">',
        '<div class="a-sp-notifications-redirect-default-img-text">{{templateData.strings.spShowNotificationRedirectMessage}}</div>',
      '</div>',
    ],
    notificationBar: [
        '<div class="asp-notifications-bar-wrapper a-sp-notifications-hidden notranslate" id="asp-notifications-bar">',
          '<img class="asp-notifications-bar-logo" src="{{templateData.images.loadingNotificationLogo}}"/>',
          '<div class="asp-notifications-bar-content">',
            '<div class="asp-notifications-bar-offers a-sp-notifications-hidden">',
              '<img class="asp-notifications-bar-image" src="{{templateData.images.moreOffersBar}}"/>',
              '<img class="asp-notifications-bar-image-animated asp-notification-bar-image-hidden" src="{{templateData.animations.moreOffersBar}}"/>',
              '<div class="asp-notifications-bar-text">{{templateData.strings.spBetterOffersNotificationBarMessage}}</div>',
            '</div>',
            '<div class="asp-notifications-bar-alt-hotels a-sp-notifications-hidden">',
              '<img class="asp-notifications-bar-image" src="{{templateData.images.hotelsBar}}"/>',
              '<img class="asp-notifications-bar-image-animated asp-notification-bar-image-hidden" src="{{templateData.animations.hotelsBar}}"/>',
              '<div class="asp-notifications-bar-text">{{templateData.strings.spSimilarHotelsNotificationMessage}}</div>',
            '</div>',
            '<div class="asp-notifications-bar-popular-hotels a-sp-notifications-hidden">',
              '<img class=asp-notifications-bar-image" src="{{templateData.images.hotelsBar}}"/>',
              '<img class="aasp-notifications-bar-image-animated asp-notification-bar-image-hidden" src="{{templateData.animations.hotelsBar}}"/>',
              '<div class="asp-notifications-bar-text">{{templateData.strings.spCityHotelNotificationMessage}}<span class="asp-notifications-bar-city-text"></span></div>',
            '</div>',
            '<div class="asp-notifications-bar-coupons a-sp-notifications-hidden">',
              '<img class="asp-notifications-bar-image" src="{{templateData.images.couponsBar}}"/>',
              '<img class="asp-notifications-bar-image-animated asp-notification-bar-image-hidden" src="{{templateData.animations.couponsBar}}"/>',
              '<div class="asp-notifications-bar-text">{{templateData.strings.spCouponsNotificationMessage}}</div>',
            '</div>',
            '<div class="asp-notifications-bar-offers-and-coupons a-sp-notifications-hidden">',
              '<img class="asp-notifications-bar-image" src="{{templateData.images.offersAndCouponsBar}}"/>',
              '<img class="asp-notifications-bar-image-animated asp-notification-bar-image-hidden" src="{{templateData.animations.offersAndCouponsBar}}"/>',
              '<div class="asp-notifications-bar-text">{{templateData.strings.spOffersAndCouponsNotificationMessage}}</div>',
            '</div>',
            '<div class="asp-notifications-bar-deals a-sp-notifications-hidden">',
              '<img class="asp-notifications-bar-image" src="{{templateData.images.specialDealsBar}}">',
              '<img class="asp-notifications-bar-image-animated asp-notification-bar-image-hidden" src="{{templateData.animations.specialDealsBar}}"/>',
              '<div class="asp-notifications-bar-text">{{templateData.strings.spBetterSpecialDealsNotificationBarMessage}}</div>',
            '</div>',
            '<div class="asp-notifications-bar-searching-deals a-sp-notifications-hidden">',
              '<img class="asp-notifications-bar-image" src="{{templateData.images.searching}}"/>',
              '<div class="asp-notifications-bar-content-two-rows">',
                '<div class="asp-notifications-bar-text">{{templateData.strings.spLoadingNotificationMessage}}</div>',
                '<div class="asp-notifications-bar-searching-subtext">{{templateData.strings.spLoadingNotificationDescriptionMessage}}</div>',
              '</div>',
            '</div>',
          '<div class="asp-notifications-bar-button">',
              '<span class="asp-notifications-bar-button-text">{{templateData.strings.spShowNotificationMessage}}</span>',
              '<span class="asp-notifications-bar-button-badge">',
                '<div class="asp-notifications-bar-button-badge-text"></div>',
              '</span>',
          '</div>',
          '</div>',
          '<div class="asp-notifications-bar-actions">',
            '<div class="asp-notifications-bar-gear-icon" id="settings-bar" style="background-image: url({{templateData.images.loadingNotificationGear}});"></div>',
            '<div class="asp-notifications-bar-close-icon" id="close-bar" style="background-image: url({{templateData.images.loadingNotificationClose}});"></div>',
          '</div>',
        '</div>',
    ],
    notificationRedirectBar:[
        '<div class="asp-notifications-redirect-bar-wrapper a-sp-notifications-hidden notranslate" id="asp-notifications-redirect-bar">',
        '<img class="asp-notifications-bar-logo" src="{{templateData.images.loadingNotificationLogo}}"/>',
        '<div class="asp-notification-bar-title">{{templateData.strings.spShowNotificationRedirectMessage}}</div>',
        '<div class="asp-notifications-bar-content">',
          '<div class="asp-notifications-bar-redirect-deal">',
            '{{#redirect.image}}',
              '<img class="asp-notifications-bar-redirect-deal-img" src="{{redirect.image}}"/>',
            '{{/redirect.image}}',
            '{{^redirect.image}}',
              '<div class="asp-blank-div"></div>',
            '{{/redirect.image}}',
            '<div class="asp-notifications-bar-redirect-deal-description">',
              '<div class="asp-notifications-bar-redirect-deal-title">{{redirect.label}}</div>',
              '<div class="asp-notifications-bar-redirect-deal-subtitle">{{redirect.availability}}</div>',
            '</div>',
            '<div class="asp-notification-bar-redirect-deal-info-wrapper">',
            '{{#redirect.infoText}}',
              '<img class="asp-notifications-bar-redirect-deal-info-img" src="{{templateData.images.info}}"/>',
              '<div class="asp-notification-bar-redirect-deal-info-box"><div class="asp-notifications-bar-redirect-deal-info-text">{{redirect.infoText}}</div></div>',
            '{{/redirect.infoText}}',
            '</div>',
          '</div>',
          '<div class="asp-notifications-bar-button" resurl="{{redirect.url}}">',
            '<span class="asp-notifications-bar-button-text">{{templateData.strings.spNotificationRedirectShowRedirectMessage}}</span>',
            '<img class="asp-notifications-bar-button-arrow" src="{{templateData.images.arrow}}"/>',
          '</div>',
        '</div>',
        '<div class="asp-notifications-bar-actions">',
          '<div class="asp-notifications-bar-gear-icon" id="settings-bar" style="background-image: url({{templateData.images.loadingNotificationGear}});"></div>',
          '<div class="asp-notifications-bar-close-icon" id="close-bar" style="background-image: url({{templateData.images.loadingNotificationClose}});"></div>',
        '</div>',
        '</div>',
    ],
    // --ende templates declarations --
  });
